name = "meater"
main = "src/index.ts"
compatibility_date = "2022-11-11"
usage_model = "bundled"
route = "dev.drivewaypitmaster.com/*"

compatibility_flags = ["streams_enable_constructors"]

[triggers]
crons = [ ]
